# Generated by Django 5.0.4 on 2024-05-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_remove_user_iduser_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Essences_idEssences',
            new_name='Essences_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Scarabs_idScarabs',
            new_name='Scarabs_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='oils_oil_id',
            new_name='oils_id',
        ),
    ]
