# Generated by Django 5.0.4 on 2024-05-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_remove_user_itens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(default=None, null=True, upload_to='static/img/'),
        ),
    ]
