from django.db import models

# Create your models here.
from django.db import models


class Essences(models.Model):
	idEssences = models.AutoField(primary_key=True)
	remnant_of_corruption = models.SmallIntegerField(default=0)
	horror = models.SmallIntegerField(default=0)
	delirium = models.SmallIntegerField(default=0)
	insanity = models.SmallIntegerField(default=0)
	hysteria = models.SmallIntegerField(default=0)
	deafening_envy = models.SmallIntegerField(default=0)
	deafening_scorn = models.SmallIntegerField(default=0)
	deafening_loathing = models.SmallIntegerField(default=0)
	deafening_spite = models.SmallIntegerField(default=0)
	deafening_zeal = models.SmallIntegerField(default=0)
	deafening_rage = models.SmallIntegerField(default=0)
	shrieking_envy = models.SmallIntegerField(default=0)
	deafening_misery = models.SmallIntegerField(default=0)
	deafening_sorrow = models.SmallIntegerField(default=0)
	deafening_greed = models.SmallIntegerField(default=0)
	deafening_torment = models.SmallIntegerField(default=0)
	deafening_fear = models.SmallIntegerField(default=0)
	deafening_woe = models.SmallIntegerField(default=0)
	deafening_anger = models.SmallIntegerField(default=0)
	deafening_contempt = models.SmallIntegerField(default=0)
	deafening_dread = models.SmallIntegerField(default=0)
	deafening_hatred = models.SmallIntegerField(default=0)
	deafening_wrath = models.SmallIntegerField(default=0)
	shrieking_dread = models.SmallIntegerField(default=0)
	shrieking_loathing = models.SmallIntegerField(default=0)
	shrieking_misery = models.SmallIntegerField(default=0)
	shrieking_scorn = models.SmallIntegerField(default=0)
	shrieking_greed = models.SmallIntegerField(default=0)
	shrieking_zeal = models.SmallIntegerField(default=0)
	deafening_suffering = models.SmallIntegerField(default=0)
	deafening_anguish = models.SmallIntegerField(default=0)
	deafening_doubt = models.SmallIntegerField(default=0)
	muttering_anger = models.SmallIntegerField(default=0)
	muttering_contempt = models.SmallIntegerField(default=0)
	muttering_fear = models.SmallIntegerField(default=0)
	muttering_greed = models.SmallIntegerField(default=0)
	muttering_hatred = models.SmallIntegerField(default=0)
	muttering_sorrow = models.SmallIntegerField(default=0)
	muttering_torment = models.SmallIntegerField(default=0)
	muttering_woe = models.SmallIntegerField(default=0)
	screaming_dread = models.SmallIntegerField(default=0)
	screaming_envy = models.SmallIntegerField(default=0)
	screaming_greed = models.SmallIntegerField(default=0)
	screaming_loathing = models.SmallIntegerField(default=0)
	screaming_misery = models.SmallIntegerField(default=0)
	screaming_scorn = models.SmallIntegerField(default=0)
	screaming_zeal = models.SmallIntegerField(default=0)
	shrieking_anger = models.SmallIntegerField(default=0)
	shrieking_contempt = models.SmallIntegerField(default=0)
	shrieking_fear = models.SmallIntegerField(default=0)
	shrieking_hatred = models.SmallIntegerField(default=0)
	shrieking_rage = models.SmallIntegerField(default=0)
	shrieking_sorrow = models.SmallIntegerField(default=0)
	shrieking_spite = models.SmallIntegerField(default=0)
	shrieking_torment = models.SmallIntegerField(default=0)
	shrieking_woe = models.SmallIntegerField(default=0)
	shrieking_wrath = models.SmallIntegerField(default=0)
	wailing_anger = models.SmallIntegerField(default=0)
	wailing_anguish = models.SmallIntegerField(default=0)
	wailing_contempt = models.SmallIntegerField(default=0)
	wailing_doubt = models.SmallIntegerField(default=0)
	wailing_fear = models.SmallIntegerField(default=0)
	wailing_greed = models.SmallIntegerField(default=0)
	wailing_hatred = models.SmallIntegerField(default=0)
	wailing_loathing = models.SmallIntegerField(default=0)
	wailing_rage = models.SmallIntegerField(default=0)
	wailing_sorrow = models.SmallIntegerField(default=0)
	wailing_spite = models.SmallIntegerField(default=0)
	wailing_suffering = models.SmallIntegerField(default=0)
	wailing_torment = models.SmallIntegerField(default=0)
	wailing_woe = models.SmallIntegerField(default=0)
	wailing_wrath = models.SmallIntegerField(default=0)
	wailing_zeal = models.SmallIntegerField(default=0)
	weeping_anger = models.SmallIntegerField(default=0)
	weeping_contempt = models.SmallIntegerField(default=0)
	weeping_doubt = models.SmallIntegerField(default=0)
	weeping_fear = models.SmallIntegerField(default=0)
	weeping_greed = models.SmallIntegerField(default=0)
	weeping_hatred = models.SmallIntegerField(default=0)
	weeping_rage = models.SmallIntegerField(default=0)
	weeping_sorrow = models.SmallIntegerField(default=0)
	weeping_suffering = models.SmallIntegerField(default=0)
	weeping_torment = models.SmallIntegerField(default=0)
	weeping_woe = models.SmallIntegerField(default=0)
	weeping_wrath = models.SmallIntegerField(default=0)
	whispering_contempt = models.SmallIntegerField(default=0)
	whispering_greed = models.SmallIntegerField(default=0)
	whispering_hatred = models.SmallIntegerField(default=0)
	whispering_woe = models.SmallIntegerField(default=0)
	screaming_woe = models.SmallIntegerField(default=0)
	shrieking_doubt = models.SmallIntegerField(default=0)
	screaming_anger = models.SmallIntegerField(default=0)
	screaming_wrath = models.SmallIntegerField(default=0)
	shrieking_anguish = models.SmallIntegerField(default=0)
	shrieking_suffering = models.SmallIntegerField(default=0)
	screaming_sorrow = models.SmallIntegerField(default=0)
	screaming_fear = models.SmallIntegerField(default=0)
	screaming_hatred = models.SmallIntegerField(default=0)
	screaming_rage = models.SmallIntegerField(default=0)
	screaming_torment = models.SmallIntegerField(default=0)
	screaming_spite = models.SmallIntegerField(default=0)
	screaming_doubt = models.SmallIntegerField(default=0)
	screaming_anguish = models.SmallIntegerField(default=0)
	screaming_contempt = models.SmallIntegerField(default=0)
	screaming_suffering = models.SmallIntegerField(default=0)
	def __str__(self) -> str:
		return f'Essence: {self.idEssences}'


class Oils(models.Model):
	oil_id = models.AutoField(primary_key=True)
	Tainted = models.SmallIntegerField(default=0)
	Golden = models.SmallIntegerField(default=0)
	Silver = models.SmallIntegerField(default=0)
	Opalescent = models.SmallIntegerField(default=0)
	Black = models.SmallIntegerField(default=0)
	Reflective = models.SmallIntegerField(default=0)
	Crimson = models.SmallIntegerField(default=0)
	Violet = models.SmallIntegerField(default=0)
	Azure = models.SmallIntegerField(default=0)
	Indigo = models.SmallIntegerField(default=0)
	Teal = models.SmallIntegerField(default=0)
	Verdant = models.SmallIntegerField(default=0)
	Amber = models.SmallIntegerField(default=0)
	Sepia = models.SmallIntegerField(default=0)
	Clear = models.SmallIntegerField(default=0)
	def __str__(self) -> str:
		return f'Oils: {self.oil_id}'
		

class Scarabs(models.Model):
	idScarabs = models.AutoField(primary_key=True)
	Winged_Reliquary = models.SmallIntegerField(default=0)
	Winged_Abyss = models.SmallIntegerField(default=0)
	Winged_Ambush = models.SmallIntegerField(default=0)
	Winged_Harbinger = models.SmallIntegerField(default=0)
	Winged_Divination = models.SmallIntegerField(default=0)
	Winged_Legion = models.SmallIntegerField(default=0)
	Winged_Ultimatum = models.SmallIntegerField(default=0)
	Winged_Breach = models.SmallIntegerField(default=0)
	Winged_Torment = models.SmallIntegerField(default=0)
	Winged_Cartography = models.SmallIntegerField(default=0)
	Winged_Blight = models.SmallIntegerField(default=0)
	Winged_Expedition = models.SmallIntegerField(default=0)
	Winged_Elder = models.SmallIntegerField(default=0)
	Winged_Sulphite = models.SmallIntegerField(default=0)
	Winged_Shaper = models.SmallIntegerField(default=0)
	Winged_Bestiary = models.SmallIntegerField(default=0)
	Polished_Legion = models.SmallIntegerField(default=0)
	Gilded_Abyss = models.SmallIntegerField(default=0)
	Gilded_Reliquary = models.SmallIntegerField(default=0)
	Gilded_Harbinger = models.SmallIntegerField(default=0)
	Gilded_Divination = models.SmallIntegerField(default=0)
	Gilded_Ambush = models.SmallIntegerField(default=0)
	Rusted_Legion = models.SmallIntegerField(default=0)
	Polished_Reliquary = models.SmallIntegerField(default=0)
	Polished_Abyss = models.SmallIntegerField(default=0)
	Gilded_Ultimatum = models.SmallIntegerField(default=0)
	Gilded_Breach = models.SmallIntegerField(default=0)
	Polished_Harbinger = models.SmallIntegerField(default=0)
	Polished_Divination = models.SmallIntegerField(default=0)
	Gilded_Cartography = models.SmallIntegerField(default=0)
	Gilded_Legion = models.SmallIntegerField(default=0)
	Gilded_Expedition = models.SmallIntegerField(default=0)
	Gilded_Torment = models.SmallIntegerField(default=0)
	Gilded_Blight = models.SmallIntegerField(default=0)
	Gilded_Sulphite = models.SmallIntegerField(default=0)
	Gilded_Shaper = models.SmallIntegerField(default=0)
	Gilded_Bestiary = models.SmallIntegerField(default=0)
	Gilded_Elder = models.SmallIntegerField(default=0)
	Polished_Cartography = models.SmallIntegerField(default=0)
	Polished_Ambush = models.SmallIntegerField(default=0)
	Rusted_Divination = models.SmallIntegerField(default=0)
	Rusted_Reliquary = models.SmallIntegerField(default=0)
	Rusted_Ambush = models.SmallIntegerField(default=0)
	Rusted_Harbinger = models.SmallIntegerField(default=0)
	Rusted_Sulphite = models.SmallIntegerField(default=0)
	Polished_Shaper = models.SmallIntegerField(default=0)
	Polished_Sulphite = models.SmallIntegerField(default=0)
	Polished_Breach = models.SmallIntegerField(default=0)
	Polished_Torment = models.SmallIntegerField(default=0)
	Polished_Elder = models.SmallIntegerField(default=0)
	Polished_Bestiary = models.SmallIntegerField(default=0)
	Rusted_Blight = models.SmallIntegerField(default=0)
	Rusted_Abyss = models.SmallIntegerField(default=0)
	Polished_Blight = models.SmallIntegerField(default=0)
	Polished_Expedition = models.SmallIntegerField(default=0)
	Rusted_Ultimatum = models.SmallIntegerField(default=0)
	Polished_Ultimatum = models.SmallIntegerField(default=0)
	Rusted_Cartography = models.SmallIntegerField(default=0)
	Rusted_Elder = models.SmallIntegerField(default=0)
	Rusted_Bestiary = models.SmallIntegerField(default=0)
	Rusted_Torment = models.SmallIntegerField(default=0)
	Rusted_Breach = models.SmallIntegerField(default=0)
	Rusted_Shaper = models.SmallIntegerField(default=0)
	Rusted_Expedition = models.SmallIntegerField(default=0)
	
	def __str__(self) -> str:
		return f'Scarabs: {self.idScarabs}'


# Create your models here.
class User(models.Model):
	idUser = models.AutoField(primary_key=True)
	name = models.CharField(max_length=45, null=True, default=None)
	nickName = models.CharField(max_length=45, null=True, default=None)
	email = models.CharField(max_length=45, null=True, default=None)
	password = models.CharField(max_length=45, null=True, default=None)
	itens = models.IntegerField(null=True, default=None)
	createdAt = models.DateTimeField()
	updatedAt = models.DateTimeField()
	Essences_idEssences = models.ForeignKey(Essences, on_delete=models.CASCADE)
	oils_oil_id = models.ForeignKey(Oils, on_delete=models.CASCADE)
	Scarabs_idScarabs = models.ForeignKey(Scarabs, on_delete=models.CASCADE)

	def __str__(self) -> str:
		return f'Nickname: {self.nickName}, Email: {self.email}'
